# Generated by Django 3.2.12 on 2023-05-25 06:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('trek_distance', models.FloatField(blank=True, null=True)),
                ('highest_altitude', models.FloatField(blank=True, null=True)),
                ('trek_durations', models.CharField(max_length=100)),
                ('meals', models.CharField(max_length=299)),
            ],
        ),
        migrations.CreateModel(
            name='TripGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('trip_durations', models.CharField(max_length=100)),
                ('highest_altitude', models.FloatField(blank=True, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=299, null=True)),
                ('group_size', models.CharField(blank=True, max_length=100, null=True)),
                ('best_season', models.CharField(blank=True, max_length=299, null=True)),
                ('brief_insight', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('includes', models.TextField(blank=True, null=True)),
                ('excludes', models.TextField(blank=True, null=True)),
                ('trip_map', models.ImageField(blank=True, null=True, upload_to='')),
                ('benefits', models.TextField(blank=True, null=True)),
                ('comprehensive_guide', models.TextField(blank=True, null=True)),
                ('packing_list', models.TextField()),
                ('frequently_asked_questions', models.CharField(blank=True, max_length=599, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.itinerary')),
                ('trip_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.tripgrade')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=299, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
