# Generated by Django 3.2.12 on 2023-05-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='package.package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=models.CharField(max_length=299),
        ),
    ]
