# Generated by Django 3.2.12 on 2023-05-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20230526_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='trip_map',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
