# Generated by Django 3.2.12 on 2023-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=199)),
                ('company_profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('about_company', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=199, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=199)),
                ('company_profile', models.CharField(blank=True, max_length=199, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('company_history', models.TextField(blank=True, null=True)),
                ('company_missions', models.TextField(blank=True, null=True)),
                ('your_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyAndPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_and_policy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_conditions', models.TextField()),
            ],
        ),
    ]
