# Generated by Django 3.2.12 on 2023-05-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='company_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
